create table if not exists public.enquiries (
 id bigint generated by default as identity primary key,
 created_at timestamptz default now(),
 name text not null,
 company text,
 phone text not null,
 email text,
 service text,
 pages text,
 message text,
 status text default 'new'
);
alter table public.enquiries enable row level security;
create policy "public can submit enquiries" on public.enquiries for insert to anon with check (true);
-- For the admin dashboard, use Supabase Auth and add authenticated-only SELECT/UPDATE policies.
create bucket if not exists documents;
