'use client';
import {useState} from 'react';
const services=[['Document Scanning','High-volume scanning with quality control and organized delivery.'],['OCR & Searchable PDF','Convert scanned pages into searchable digital documents.'],['Document Indexing','Structured naming, metadata and folder-wise indexing.'],['Data Entry','Accurate data entry and document-based processing.'],['PDF Processing','Renaming, splitting, merging, compression and PDF/A workflows.'],['Manpower Services','Trained manpower for scanning, indexing and back-office operations.']];
export default function Home(){const [open,setOpen]=useState(false);const [sent,setSent]=useState(false);async function submit(e:any){e.preventDefault();const f=new FormData(e.currentTarget);try{await fetch('/api/enquiry',{method:'POST',body:f});setSent(true);e.currentTarget.reset()}catch{setSent(true)}}return <main>
<header><div className="nav"><div className="brand"><span className="logo">NG</span><span>NG <b>SOLUTIONZ</b></span></div><nav><a href="#services">Services</a><a href="#industries">Industries</a><a href="#about">About</a><a href="#contact">Contact</a></nav><button className="navbtn" onClick={()=>setOpen(true)}>Get a Quote</button></div></header>
<section className="hero"><div className="heroText"><div className="eyebrow">DIGITAL DOCUMENT SOLUTIONS</div><h1>Turn paper records into <span>smart digital assets.</span></h1><p>Professional document scanning, OCR, indexing, data entry and record management for organizations that need speed, accuracy and secure handling.</p><div className="actions"><button onClick={()=>setOpen(true)}>Request a Quote →</button><a href="https://wa.me/917259767438" target="_blank">WhatsApp Us</a></div><div className="stats"><div><strong>6+</strong><small>Core services</small></div><div><strong>QC</strong><small>Quality workflow</small></div><div><strong>OCR</strong><small>Searchable records</small></div></div></div><div className="heroCard"><div className="cardTop"><span>DOCUMENT WORKFLOW</span><span className="live">● SECURE</span></div><div className="flow"><div>01 <b>Collect</b><small>Records & files</small></div><i>→</i><div>02 <b>Digitize</b><small>Scan + OCR</small></div><i>→</i><div>03 <b>Deliver</b><small>Indexed output</small></div></div><div className="progress"><span></span></div><small>Organized • Searchable • Ready to use</small></div></section>
<section id="services" className="section"><div className="sectionHead"><div><div className="eyebrow">WHAT WE DO</div><h2>Services built for document-heavy work.</h2></div><p>From bulk scanning to structured digital records, our workflow is designed around practical business operations.</p></div><div className="grid">{services.map((s,i)=><article className="service" key={s[0]}><div className="num">0{i+1}</div><h3>{s[0]}</h3><p>{s[1]}</p><a href="#contact">Discuss service →</a></article>)}</div></section>
<section id="industries" className="dark"><div className="sectionHead"><div><div className="eyebrow">INDUSTRIES</div><h2>Digital records for every department.</h2></div><p>Suitable for banks, hospitals, offices, schools, government departments, legal teams and other document-intensive organizations.</p></div><div className="industryGrid">{['Banks & Finance','Hospitals','Government','Schools & Colleges','Corporate Offices','Legal Firms'].map(x=><div key={x}>{x}<span>↗</span></div>)}</div></section>
<section id="about" className="section about"><div><div className="eyebrow">WHY NG SOLUTIONZ</div><h2>A practical partner for your digital records.</h2></div><div className="aboutText"><p>We combine scanning, quality control, indexing and digital document processing into a straightforward workflow that teams can actually use.</p><div className="checks"><span>✓ Structured file naming</span><span>✓ Quality-controlled output</span><span>✓ Searchable PDF workflows</span><span>✓ Confidential handling</span></div></div></section>
<section id="contact" className="cta"><div><div className="eyebrow">START A PROJECT</div><h2>Have a document digitization requirement?</h2><p>Tell us what you need. We'll get back to you with the next steps.</p></div><button onClick={()=>setOpen(true)}>Request a Quote →</button></section>
<footer><div><div className="brand"><span className="logo">NG</span><span>NG <b>SOLUTIONZ</b></span></div><p>Document scanning • OCR • Indexing • Data Entry • PDF Processing • Manpower</p></div><div><b>Contact</b><p>7259767438<br/>ngsolutionz82@gmail.com<br/>Bangalore, Karnataka – 560027</p></div></footer>
{open&&<div className="modal"><div className="modalBox"><button className="close" onClick={()=>setOpen(false)}>×</button><div className="eyebrow">REQUEST A QUOTE</div><h2>Tell us about your project</h2>{sent?<div className="success">✓ Thanks. Your enquiry has been submitted.</div>:<form onSubmit={submit}><input name="name" placeholder="Your name" required/><input name="company" placeholder="Company / organization"/><input name="phone" placeholder="Phone number" required/><input name="email" type="email" placeholder="Email address"/><select name="service" defaultValue=""><option value="" disabled>Select service</option>{services.map(s=><option key={s[0]}>{s[0]}</option>)}</select><input name="pages" placeholder="Approx. pages / records"/><textarea name="message" placeholder="Tell us about your requirement"></textarea><button type="submit">Submit Enquiry →</button></form>}</div></div>}
</main>}
